- name: download kubectl
  get_url:
    url: '{{ kubectl_binary }}'
    dest: '{{ kubectl_install_target }}'
    mode: 0755

- name: create .kube folder
  file:
    path: '{{ vagrant_home }}/.kube'
    state: directory
    mode: 0755

- name: download helm
  get_url:
    url: '{{ helm_binary }}'
    dest: '/tmp/helm.tar.gz'
    mode: 0755
    checksum: '{{ helm_checksum }}'

- name: unarchive helm
  unarchive:
    src: '/tmp/helm.tar.gz'
    remote_src: true
    dest: '/tmp'
    mode: 0755

- name: copy helm binary
  copy:
    src: /tmp/linux-amd64/helm
    dest: '{{ helm_install_target }}'
    mode: 0755
    remote_src: yes

- name: recursively change permissions of k8s folders
  file:
    path: '{{ vagrant_home }}/{{ item }}'
    state: directory
    mode: 0777
    recurse: yes
  with_items:
  - .kube
