- name: download kubectl
  get_url:
    url: 'https://storage.googleapis.com/kubernetes-release/release/v{{kubectl_version}}/bin/linux/amd64/kubectl'
    dest: '{{ kubectl_install_target }}'
    mode: 0755

- name: create .kube folder
  file:
    path: '{{ vagrant_home }}/.kube'
    state: directory
    mode: 0755

- name: download helm
  get_url:
    url: 'https://get.helm.sh/helm-v{{helm_version}}-linux-amd64.tar.gz'
    dest: '/tmp/helm.tar.gz'
    mode: 0755
    checksum: '{{ helm_checksum }}'

- name: unarchive helm
  unarchive:
    src: '/tmp/helm.tar.gz'
    remote_src: true
    dest: '/tmp'
    mode: 0755

- name: copy helm binary
  copy:
    src: /tmp/linux-amd64/helm
    dest: '{{ helm_install_target }}'
    mode: 0755
    remote_src: yes

- name: download rke
  get_url:
    url: 'https://github.com/rancher/rke/releases/download/v{{rke_version}}/rke_linux-amd64'
    dest: '/usr/local/bin/rke'
    mode: 0755
    checksum: "{{rke_checksum}}"

- name: recursively change permissions of k8s folders
  file:
    path: '{{ vagrant_home }}/{{ item }}'
    state: directory
    mode: 0777
    recurse: yes
  with_items:
  - .kube
