---
- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: install required packages
      become: true
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
      - curl
      - unzip
      - vim
      - jq
      - git
      - python-apt
      - apt-transport-https
      - gnupg
      - software-properties-common
      - uuid-runtime
      register: task_result
      until: task_result is success
      retries: 3
      delay: 20
      changed_when: false

- hosts: localhost
  connection: local
  vars:
    machine_host: 'devbox'
  roles:
     - { role: hostname, become: true }
     - { role: terraform, become: true }
     - { role: openstack, become: true }
     - { role: kube, become: true }
     - { role: docker, become: true }
